export const icons = {
  arrowDown: require("../assets/media/icons/angel-down-thin.svg"),
  arrowLeft: require("../assets/media/icons/angel-left-thin.svg"),
  arrowRight: require("../assets/media/icons/angel-right-thin.svg"),
  arrowUp: require("../assets/media/icons/angel-up-thin.svg"),
  checkoutFilled: require("../assets/media/icons/checkout-filled.svg"),
  checkoutLined: require("../assets/media/icons/checkout-lined.svg"),
  dashboardFilled: require("../assets/media/icons/dashboard-filled.svg"),
  dashboardLined: require("../assets/media/icons/dashboard-lined.svg"),
  edit: require("../assets/media/icons/edit.svg"),
  gearFilled: require("../assets/media/icons/gear-filled.svg"),
  gearLined: require("../assets/media/icons/gear-lined.svg"),
  logout: require("../assets/media/icons/log-out.svg"),
  magnifier: require("../assets/media/icons/magnifier-lined.svg"),
  minus: require("../assets/media/icons/minus-thin.svg"),
  plus: require("../assets/media/icons/plus-thin.svg"),
  productFilled: require("../assets/media/icons/product-filled.svg"),
  productLined: require("../assets/media/icons/product-lined.svg"),
  tagFilled: require("../assets/media/icons/tag-filled.svg"),
  tagLined: require("../assets/media/icons/tag-lined.svg"),
  timeFilled: require("../assets/media/icons/time-filled.svg"),
  timeLined: require("../assets/media/icons/time-lined.svg"),
  user: require("../assets/media/icons/user.svg"),
  userDefault: require("../assets/media/icons/user-default.svg"),
  info: require("../assets/media/icons/info.svg"),
  infoDefault: require("../assets/media/icons/info-default.svg"),
};
